version: '3.8'

services:
  znhd-service:
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis-condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme123} --appendonly yes
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  redis_data:
